### ISSUE TITLE
Multiple use of MediaRecorder creates too many AudioContext objects

### ISSUE THREAD

**Issue by BenjaminAbdi** [kbumsik/opus-media-recorder#18]
Hi Kim, 
First of all thank you, as we're able to solve the problem of uploading audio to our servers from iPad browsers, which is key in our applications :-)

I however had an issue of inconsistent behaviour. 
After making several calls to the MediaRecorder class (due to recording multiple times in a row), I got an error popping. 

> TypeError: null is not an object (evaluating 't.context.sampleRate')

The reason for that is the fact we're creating a new AudioContext at each MediaRecorder call: `this.context = new AudioContext();`It seems there is a browser limitation to how many AudioContext can be built (see [here](https://stackoverflow.com/questions/45528945/audiocontext-samplerate-returning-null-after-being-read-8-times) and [there](https://github.com/otalk/hark/issues/38)).

*Edit*
[This patch](https://github.com/kbumsik/opus-media-recorder/compare/master...BenjaminAbdi:patch-2) allows to remove multiple audio context creation, but keeping the creation of the initial AudioContext within the fallback of a user-gesture.

**Comment by kbumsik** [comment]
Hi,
I'm happy to hear you find it helpful :)

Thank you very much for reporting. I though it is automatically garbage-collected. However, I can not accept your patch because this patch will disallow users to create multiple MediaRecorders at a time, and I'm not sure if running multiple MediaRecorder is important.

Another possible fix is that [closing the `AudioContext`](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/close) when you call `MediaRecorder.close()`. Do you think it will resolve the problem you have? I will test this fix this weekend.

**Comment by BenjaminAbdi** [comment]
I'm not sure this would disallow to create multiple at a time (at least I was able to create 2). But anyway I'm not very proud of the patch :-)

My use case is:
- I want to play the audio recorded in the browser (in wav to be compatible with all browsers) ;
- I want to stream the audio ogg/webm to the server, by cloning the stream;
- I want to repeat that several times per session.

So I guess closing the MediaRecorder and the AudioContext doing so would probably work as well :-)

**Comment by prtcl** [comment]
hi! I've run into this same issue. the above patch might resolve it, or also maybe consider adding a non-standard constructor option to pass in your own context instance. in my app there is already a context running, so it's easy to reuse the same one. I am not sure how many others have this same use case though

**Comment by kbumsik** [comment]
@BenjaminAbdi @prtcl I believe ee2fa8a fixes the problem. The new release `0.7.18` have the patch. Could you test if the patch worked for you? It took some days to apply this patch because I cannot reproduce the issue (though it looks obvious). So I'm not 100% sure about this patch. It would be great if I can get any minimal example that can reproduce the problem.

@prtcl I'm not sure about the suggestion. The goal of this project it to reimplement MediaRecorder therefore I would be very cautious about adding a non-standard option unless inevitable. Let's see the patch works first.

**Comment by BenjaminAbdi** [comment]
@kbumsik Your patch solves the problem, thanks a lot :-)
