### ISSUE TITLE
installing via npm

### ISSUE THREAD

**Issue by chris-rudmin** [kbumsik/opus-media-recorder#5]
I was hoping to be able to do `npm install opus-media-recorder` and then `import MediaRecorder from 'opus-media-recoder';` However there are no files in the npm distribution.

Could you document if there is any magic that you need to add to `webpack.config` to get this to work? 

It should be possible to specify an emscripten `Module.locate` which could point to the wasm files hosted in jsdelivr to make importing this project easier.

**Comment by kbumsik** [comment]
Hi!
I glad to see you here :). And yes. I think the NPM package is should empty for now.
I have been focusing on only the feature developments and I have not done any configurations for general release yet. Actually I finished the libogg/libwebm integration just yesterday.

Since I reached the original goal now I should do NPM and webpack stuff. I will finish it in a couple of days.

Before start working on it, is there any specific ways you wish to work? I am originally a C/Python dev and I don't know much experience on the distribution systems of front-end npm packages.

**Comment by chris-rudmin** [comment]
I think a common workflow is to do `npm install opus-media-recorder` and then `import MediaRecorder from 'opus-media-recoder';` and people expect it to work in their react project (it currently doesn't work like this in opus-recorder and I am looking at fixing it). 

It would probably be nice to distribute the un-minified transpiled sources instead of a umd library, which can make bundling the source more efficient.

Looks like a super awesome project 👍

**Comment by kbumsik** [comment]
@chris-rudmin Hi Thanks your advice :)
It took a month to figure out the best way to work with ES6 and bundlers(e.g. webpack), but I finally made it!

Please take a look at [the updated README](https://github.com/kbumsik/opus-media-recorder#working-with-a-bundler) and [webpack example](https://github.com/kbumsik/opus-media-recorder/tree/master/example/webpack).

Note that because the ways to load worker and binaries are different in every bundlers, I have to introduce a non-standard option: `workerOptions`.
